version: "2"
services:
  #PHP Container Settings
  phpfpm:
    container_name: containe-php
    restart: always
    build: php
    ports:
      - "9000:9000"
    links:
      - mysql
      - redis
    environment:
        PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
        XDEBUG_CONFIG: remote_host=0.0.0.0
    volumes:
      - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
      - ../local.loc:/var/www/local_server
      - ./logs/php:/var/log/php-fpm
  #NGINX Container Settings
  nginx:
    container_name: containe-nginx
    restart: always
    image: nginx
    ports:
      - "8001:81"
    links:
      - phpfpm:phpfpm
    volumes:
      - ./nginx/config/vhost.conf:/etc/nginx/conf.d/default.conf
      - ../local.loc:/var/www/local_server
      - ./logs/nginx:/var/log/nginx
  #MYSQL Container Settings
  mysql:
    container_name: containe-mysql
    restart: always
    image: mysql:5.6.21
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mytaxi
    volumes:
      - ./mysql/databases:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
  #REDIS Container Settings
  redis:
    container_name: containe-redis
    restart: always
    image: redis:3.0.6-alpine
    ports:
      - "6380:6379"